### ISSUE TITLE
Error: GlueError: XML parse exception: Premature end of file.

### ISSUE THREAD

**Issue by mrubiobu** [giffordlabcvr/HCV-GLUE#3]
Hi,

First of all I would like to congratulate you on the great job on the GLUE software and the HCV genotyping.

I am having some trouble trying to execute the software in my computer. I did the Native installation of gluetools.sh and I followed the user guide. It actually worked for genotyping, but when I try to run the Deep Sequencing data analysis it crashes. I installed the Extensions for NCBI-HCV and the PHE-HCV-DRUG-RESISTANCE by running the run file command. When I am trying to analyze the ngsDATA.bam or I try to use my data I get this error

GLUE Version 1.1.113
Copyright (C) 2015-2020 The University of Glasgow
This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you
are welcome to redistribute it under certain conditions. For details see
GNU Affero General Public License v3: http://www.gnu.org/licenses/

Mode path: /
GLUE> project hcv
OK
Mode path: /project/hcv
GLUE> module phdrReportingController invoke-
invoke-consumes-binary-function    invoke-function                    
GLUE> module phdrReportingController invoke-function report
reportBam            reportBamAsHtml      reportFasta          reportFastaAsHtml    reportFastaWeb       
GLUE> module phdrReportingController invoke-function reportBamAsHtml ngsData.bam 15.0 ngsData.html
Error: GlueError: XML parse exception: Premature end of file.
Line 171 of <eval>: 	at command (<eval>:171)
	at <anonymous> (phdrReportingController.js:1568)
	at inMode (<eval>:178)
	at recogniseFasta (phdrReportingController.js:1567)
	at <anonymous> (phdrReportingController.js:901)
	at inSession (<eval>:226)
	at reportBam (phdrReportingController.js:861)
	at reportBamAsHtml (phdrReportingController.js:52)
Cause: XML parse exception: Premature end of file.
Cause: Premature end of file.
Mode path: /project/hcv

Does anyone else have this problem?

Thank You in advance,

**Comment by mrubiobu** [comment]
I kind of found a solution, I was using ncbi-blast-2.16. I switched to blast 2.2.31 and reinstalled the Extensions and now it runs smooth and fine.

Cheers

**Comment by robjgiff** [comment]
Hi,

Thank you for your kind words about GLUE and HCV-GLUE! I'm glad to hear that the genotyping feature is working for you.

The "XML parse exception: Premature end of file" error often points to a problem reading or processing an XML file that GLUE expects to be complete. Since it occurs specifically during deep sequencing analysis, possible causes could include:

1.  **Corrupted or Incomplete BAM File**: This is one of the most common reasons for this error. If the BAM file is truncated or has an unexpected format issue, GLUE might fail when attempting to parse associated XML metadata or alignments. Running a check with `samtools` or re-generating the BAM file could help identify or resolve this issue.

2.  **Disk Space or File Access Permissions**: If GLUE cannot fully access or write to the BAM file or the output location, it might halt processing prematurely. Ensuring ample disk space and correct file permissions could help prevent this.

3.  **Extension-Specific Configuration or Module Dependencies**: Some extensions, like the PHE-HCV-DRUG-RESISTANCE extension, may require access to additional configuration files or dependencies. If there is a misconfiguration or if a required XML file is incomplete, this could trigger the error.

Based on past experience, checking for a corrupted BAM file may be the most effective first steps. Let me know if any of this seems applicable, or if you'd like to explore further troubleshooting.

At the moment, I'm mainly focused on other GLUE projects, most of which don't involve the use of deep sequencing data, so I'm sorry I can't offer more specific advice. I understand that the MRC-University of Glasgow Centre for Virus Research (CVR) is actively recruiting support staff to enhance support for HCV-GLUE, but for the time being, direct support may be limited.

If you continue to encounter issues after checking these areas, please feel free to reach out again—while support is limited at the moment, I’ll do my best to assist as time allows.

Kind regards,

Rob

**Comment by robjgiff** [comment]
Just saw your second email - that's great to hear and good to know about!
Thanks,
Rob
